# spring.application.name=arquiteturaSpring
# spring.jpa.show_sql=true

# Definit a inicialização dos Beans de forma tardia. O padrão é a não utilizar a inicialização tarida.
#spring.main.lazy-initialization=true

# Dentro do application.properties é possível criar propriedades personalizadas
#app.config.variable=valor

## doc -> https://docs.spring.io/spring-boot/docs/3.2.5/reference/htmlsingle/#appendix.application-properties

# É importante lembrar que não é possível utilizar os dois arquivos ao mesmo tempo,
# mas é possível migrar uma aplicação que já utiliza o application.properties para o application.yml